export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_ITEMS = "UPDATE_ITEMS";
export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_COUPONS = "UPDATE_COUPONS";
export const UPDATE_ORDERS = "UPDATE_ORDERS";

